input_columns: # Names of the input columns (features) of the csv files / datasets (used for training, inference and evaluation)
  - process.b1.capacity
  - process.b2.capacity
  - process.b3.capacity
  - process.b4.capacity
  - property.price
  - property.product
  - property.winner
output_columns: # Names of the output columns (features) of the csv files / datasets (used for training, inference and evaluation)
  - verification.time 
output_pickle_path: "output/pickle.pkl" # Relative path (to repo root) of output pickle file
